# SPDX-FileCopyrightText: Copyright (c) [2025-2026] [Sergei Mukhin]
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "sergeim-xembly"
SPDX-PackageSupplier = "Sergei Mukhin <sergei_mukhin@outlook.com>"
SPDX-PackageDownloadLocation = "https://github.com/svmukhin/sergeim-xembly"

[[annotations]]
path = [
  ".gitignore",
  ".markdownlint-cli2.yaml",
  "release-please-config.json",
  ".release-please-manifest.json",
  "**.md",
  "**/*.runsettings",
  "**/*.props",
  "**/*.csproj",
  "**/*.sln"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) [2025-2026] [Sergei Mukhin]"
SPDX-License-Identifier = "MIT"
